<!DOCTYPE html>
<html>

  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="description" content="Practical-machine-learning : Project work for Coursera Course">

    <link rel="stylesheet" type="text/css" media="screen" href="stylesheets/stylesheet.css">

    <title>Practical-machine-learning</title>
  </head>

  <body>

    <!-- HEADER -->
    <div id="header_wrap" class="outer">
        <header class="inner">
          <a id="forkme_banner" href="https://github.com/sjel123/Practical-Machine-Learning">View on GitHub</a>

          <h1 id="project_title">Practical-machine-learning</h1>
          <h2 id="project_tagline">Project work for Coursera Course</h2>

            <section id="downloads">
              <a class="zip_download_link" href="https://github.com/sjel123/Practical-Machine-Learning/zipball/master">Download this project as a .zip file</a>
              <a class="tar_download_link" href="https://github.com/sjel123/Practical-Machine-Learning/tarball/master">Download this project as a tar.gz file</a>
            </section>
        </header>
    </div>

    <!-- MAIN CONTENT -->
    <div id="main_content_wrap" class="outer">
      <section id="main_content" class="inner">
        <p>
</p>





<p></p>

<p></p>Practical Machine Learning Prediction Assignment



<p>

</p>



<p></p>









<p></p>

<p></p>

<p></p>

<div id="header">
<h1>
<a id="practical-machine-learning-prediction-assignment" class="anchor" href="#practical-machine-learning-prediction-assignment" aria-hidden="true"><span class="octicon octicon-link"></span></a>Practical Machine Learning Prediction Assignment</h1>
<h4>
<a id="scott-j" class="anchor" href="#scott-j" aria-hidden="true"><span class="octicon octicon-link"></span></a><em>Scott J</em>
</h4>
<h4>
<a id="thursday-november-06-2014" class="anchor" href="#thursday-november-06-2014" aria-hidden="true"><span class="octicon octicon-link"></span></a><em>Thursday, November 06, 2014</em>
</h4>
</div>

<div id="background">
<h1>
<a id="background" class="anchor" href="#background" aria-hidden="true"><span class="octicon octicon-link"></span></a>Background</h1>
<p>Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: <a href="http://groupware.les.inf.puc-rio.br/har">http://groupware.les.inf.puc-rio.br/har</a> (see the section on the Weight Lifting Exercise Dataset).</p>
</div>

<div id="data">
<h1>
<a id="data" class="anchor" href="#data" aria-hidden="true"><span class="octicon octicon-link"></span></a>Data</h1>
<p>The training data for this project are available here: <a href="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv">https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv</a> The test data are available here: <a href="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv">https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv</a> The data for this project come from this source: <a href="http://groupware.les.inf.puc-rio.br/har">http://groupware.les.inf.puc-rio.br/har</a>.</p>
</div>

<div id="preprocessing">
<h1>
<a id="preprocessing" class="anchor" href="#preprocessing" aria-hidden="true"><span class="octicon octicon-link"></span></a>Preprocessing</h1>
<div id="load-data">
<h2>
<a id="load-data" class="anchor" href="#load-data" aria-hidden="true"><span class="octicon octicon-link"></span></a>Load Data</h2>
<pre><code>library(RCurl)
data &lt;- getURL("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv",  ssl.verifypeer=0L, followlocation=1L)
data1 &lt;- getURL("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv",  ssl.verifypeer=0L, followlocation=1L)
training &lt;- read.csv(text=data)
testing &lt;- read.csv(text=data1)
dim(training)</code></pre>
<pre><code>## [1] 19622   160</code></pre>
</div>

<div id="data-filtering">
<h2>
<a id="data-filtering" class="anchor" href="#data-filtering" aria-hidden="true"><span class="octicon octicon-link"></span></a>Data Filtering</h2>
<ol>
<li>Create tidy data set by removing columns removing columns with insufficient data. 67 columns only have 406 of 19622 values. Remove these columns</li>
<li>Remove data columns that contain non informative descriptors (x, user_name, raw time stamp 1 and 2, “new_window” and “num_window”)</li>
<li>Remove columns of data with near zero varaince</li>
</ol>
<pre><code>library(caret)
training &lt;- training[,which(colSums(!is.na(training))&gt;500)]
training &lt;- training[,8:ncol(training)]
training &lt;- training[,which(nearZeroVar(training, saveMetrics = TRUE)$nzv=="FALSE")]</code></pre>
</div>

<div id="splitting-data-in-training-and-testing-for-model-cross-validation">
<h2>
<a id="splitting-data-in-training-and-testing-for-model-cross-validation" class="anchor" href="#splitting-data-in-training-and-testing-for-model-cross-validation" aria-hidden="true"><span class="octicon octicon-link"></span></a>Splitting data in training and testing for model cross validation</h2>
<p>Split the data: 60% for training, 40% for testing</p>
<pre><code>trainIndex &lt;- createDataPartition(y = training$classe, p=0.6,list=FALSE);
trainingP &lt;- training[trainIndex,];
testingP &lt;- training[-trainIndex,];
dim(trainingP)</code></pre>
<pre><code>## [1] 11776    53</code></pre>
<pre><code>dim(testingP)</code></pre>
<pre><code>## [1] 7846   53</code></pre>
</div>

<div id="create-models">
<h2>
<a id="create-models" class="anchor" href="#create-models" aria-hidden="true"><span class="octicon octicon-link"></span></a>Create Models</h2>
<p>A number of different models including Random Forest, Gradient boosted mode, naive bayes, k-nearest neighbors, support vector machine and Linear discriminant analysis were tuned and tested. The random forest algorthim gave the highest accuracy was selected for further development. Due to performance issues the other algorthim are not presented</p>
<pre><code>#parallel computing for multi-core to improve performance
library(doParallel)
registerDoParallel(makeCluster(detectCores()))
#Random Forest model
mod1 &lt;- train(classe ~ ., data = trainingP, method = "rf")

pred1 &lt;- predict(mod1,testingP)
c1 &lt;- confusionMatrix(pred1, testingP$classe)
c1</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 2228    4    0    0    0
##          B    3 1512   11    0    0
##          C    0    2 1352   20    4
##          D    0    0    5 1266    5
##          E    1    0    0    0 1433
## 
## Overall Statistics
##                                         
##                Accuracy : 0.993         
##                  95% CI : (0.991, 0.995)
##     No Information Rate : 0.284         
##     P-Value [Acc &gt; NIR] : &lt;2e-16        
##                                         
##                   Kappa : 0.991         
##  Mcnemar's Test P-Value : NA            
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             0.998    0.996    0.988    0.984    0.994
## Specificity             0.999    0.998    0.996    0.998    1.000
## Pos Pred Value          0.998    0.991    0.981    0.992    0.999
## Neg Pred Value          0.999    0.999    0.998    0.997    0.999
## Prevalence              0.284    0.193    0.174    0.164    0.184
## Detection Rate          0.284    0.193    0.172    0.161    0.183
## Detection Prevalence    0.284    0.194    0.176    0.163    0.183
## Balanced Accuracy       0.999    0.997    0.992    0.991    0.997</code></pre>
<p>The out of sample error rate is expected to be 0.701%. This was determined by cross validation on the 40% of the data that was not used to train the model</p>
</div>

<p></p>
</div>

<div id="conclusion">
<h1>
<a id="conclusion" class="anchor" href="#conclusion" aria-hidden="true"><span class="octicon octicon-link"></span></a>Conclusion:</h1>
<p>Random Forest produced an very accurate prediction with greater then 99.3%.</p>
</div>

<div id="test-set-prediction">
<h1>
<a id="test-set-prediction" class="anchor" href="#test-set-prediction" aria-hidden="true"><span class="octicon octicon-link"></span></a>Test Set Prediction</h1>
<p>The prediction for the unknown test set is:</p>
<pre><code>ScoreTest &lt;- testing[,names(testing) %in% names(trainingP)]
answers = predict(mod1,ScoreTest)

answers</code></pre>
<pre><code>##  [1] B A B A A E D B A A B C B A E E A B B B
## Levels: A B C D E</code></pre>
</div>

<p></p>







<p>
</p>
      </section>
    </div>

    <!-- FOOTER  -->
    <div id="footer_wrap" class="outer">
      <footer class="inner">
        <p class="copyright">Practical-machine-learning maintained by <a href="https://github.com/sjel123">sjel123</a></p>
        <p>Published with <a href="http://pages.github.com">GitHub Pages</a></p>
      </footer>
    </div>

    

  </body>
</html>
